# Generated by Django 4.1.3 on 2022-11-23 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('issues_id', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('issues_type', models.CharField(max_length=20)),
                ('issues_title', models.CharField(max_length=50)),
                ('issues_description', models.TextField()),
                ('issues_reporter', models.CharField(max_length=50)),
                ('issues_assignee', models.CharField(max_length=50)),
                ('issues_status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('projects_id', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('projects_description', models.TextField()),
                ('projects_title', models.CharField(max_length=50)),
                ('projects_creator', models.CharField(max_length=50)),
            ],
        ),
    ]
